# hyprpaper.conf
# Обои лежат в ~/.dotfiles/configs/wallpapers/wallpaper.jpg
# Положи туда свой файл (jpg/png)

preload = ~/.dotfiles/configs/wallpapers/wallpaper.jpg
wallpaper = ,~/.dotfiles/configs/wallpapers/wallpaper.jpg

# Если у тебя несколько мониторов:
# wallpaper = DP-1,~/.dotfiles/configs/wallpapers/wallpaper.jpg
# wallpaper = HDMI-A-1,~/.dotfiles/configs/wallpapers/wallpaper.jpg

ipc = off
splash = false
